ci: Use meson subprojects instead of gvsbuild
1. gvsbuild has broken CI multiple times in the past while
2. gvsbuild main branch requires python 3.8, and we only have 3.7
3. Older gvsbuild commits / tags have broken URLs, and even if you fix
   them, the glib version is too old
4. gvsbuild actually takes a very long time to build everything

We have an openssl project now. Not suitable for production use, but
it's fine for CI.

Need newer Meson to be able to use --vsenv reliably:

```
[...]
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\mesonbuild\mesonlib\vsenv.py", line 96, in _setup_vsenv
    k, v = bat_line.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```